CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "GlobalConfig" (
                                "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                "LastPolled" timestamp with time zone,
                                "Enabled" boolean NOT NULL DEFAULT TRUE,
                                CONSTRAINT "PK_GlobalConfig" PRIMARY KEY ("Id")
);

CREATE TABLE tenants (
                         "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
                         "Name" character varying(255) NOT NULL,
                         "LitiumBaseUrl" character varying(255) NOT NULL,
                         "ServiceAccountToken" character varying(255) NOT NULL,
                         "OrderCount" integer NOT NULL DEFAULT 0,
                         "CurrentlyFetching" boolean NOT NULL DEFAULT FALSE,
                         "FetchedFrom" timestamp with time zone,
                         "FetchedUntil" timestamp with time zone,
                         "LastPolled" timestamp with time zone,
                         "PingReachable" boolean NOT NULL DEFAULT FALSE,
                         "Enabled" boolean NOT NULL DEFAULT TRUE,
                         "IsB2B" boolean NOT NULL DEFAULT FALSE,
                         CONSTRAINT "PK_tenants" PRIMARY KEY ("Id")
);

CREATE TABLE orders (
                        "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        "TenantId" uuid NOT NULL,
                        "LitiumOrderId" text NOT NULL,
                        "CreatedDate" timestamp with time zone NOT NULL,
                        "TotalValueIncVat" integer NOT NULL,
                        "TotalValueExcVat" integer NOT NULL,
                        "Currency" character varying(3) NOT NULL,
                        "ChannelName" character varying(255) NOT NULL,
                        CONSTRAINT "PK_orders" PRIMARY KEY ("Id"),
                        CONSTRAINT "FK_orders_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_orders_tenant_litium ON orders ("TenantId", "LitiumOrderId");
CREATE INDEX idx_orders_composite_dash ON orders ("CreatedDate", "TenantId") INCLUDE ("TotalValueIncVat");

CREATE MATERIALIZED VIEW v_mat_daily_tenant_rollup AS
SELECT
    DATE("CreatedDate") as "CreatedDate",
    "TenantId",
    COUNT("Id") AS "Volume",
    SUM("TotalValueIncVat") AS "Revenue"
FROM orders
GROUP BY DATE("CreatedDate"), "TenantId";

CREATE MATERIALIZED VIEW v_mat_daily_global_rollup AS
SELECT
    "CreatedDate",
    SUM("Volume") AS "GlobalVolume",
    SUM("Revenue") AS "GlobalRevenue"
FROM v_mat_daily_tenant_rollup
GROUP BY "CreatedDate";

CREATE UNIQUE INDEX uq_mat_tenant_rollup ON v_mat_daily_tenant_rollup("CreatedDate", "TenantId");
CREATE UNIQUE INDEX uq_mat_global_rollup ON v_mat_daily_global_rollup("CreatedDate");