CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE global_config (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    last_polled timestamp with time zone,
    enabled boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_global_config PRIMARY KEY (id)
);

CREATE TABLE tenants (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(255) NOT NULL,
    litium_base_url character varying(255) NOT NULL,
    service_account_token character varying(255) NOT NULL,
    order_count integer NOT NULL DEFAULT 0,
    currently_fetching boolean NOT NULL DEFAULT FALSE,
    fetched_from timestamp with time zone,
    fetched_until timestamp with time zone,
    last_polled timestamp with time zone,
    ping_reachable boolean NOT NULL DEFAULT FALSE,
    enabled boolean NOT NULL DEFAULT TRUE,
    is_b2b boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);

CREATE TABLE orders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    litium_order_id text NOT NULL,
    created_date timestamp with time zone NOT NULL,
    total_value_inc_vat integer NOT NULL,
    total_value_exc_vat integer NOT NULL,
    currency character varying(3) NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_orders_tenant_litium ON orders (tenant_id, litium_order_id);
CREATE INDEX idx_orders_composite_dash ON orders (created_date, tenant_id) INCLUDE (total_value_inc_vat);

CREATE MATERIALIZED VIEW v_mat_daily_tenant_rollup AS
SELECT 
    DATE(created_date) AS created_date,
    tenant_id,
    COUNT(id) AS volume,
    SUM(total_value_inc_vat) AS revenue
FROM orders
WHERE created_date >= CURRENT_DATE - INTERVAL '730 days'
GROUP BY DATE(created_date), tenant_id;

CREATE MATERIALIZED VIEW v_mat_daily_global_rollup AS
SELECT 
    created_date,
    SUM(volume) AS global_volume,
    SUM(revenue) AS global_revenue
FROM v_mat_daily_tenant_rollup
GROUP BY created_date;

CREATE UNIQUE INDEX uq_mat_tenant_rollup ON v_mat_daily_tenant_rollup(created_date, tenant_id);
CREATE UNIQUE INDEX uq_mat_global_rollup ON v_mat_daily_global_rollup(created_date);

CREATE VIEW v_unified_daily_tenant_rollup AS
SELECT created_date, tenant_id, volume, revenue
FROM v_mat_daily_tenant_rollup
WHERE created_date < CURRENT_DATE
UNION ALL
SELECT DATE(created_date), tenant_id, COUNT(id), SUM(total_value_inc_vat)
FROM orders
WHERE created_date >= CURRENT_DATE
GROUP BY DATE(created_date), tenant_id;

CREATE VIEW v_unified_daily_global_rollup AS
SELECT created_date, global_volume, global_revenue
FROM v_mat_daily_global_rollup
WHERE created_date < CURRENT_DATE
UNION ALL
SELECT created_date, SUM(volume), SUM(revenue)
FROM v_unified_daily_tenant_rollup
WHERE created_date >= CURRENT_DATE
GROUP BY created_date;