/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IntranetRouteImport } from './routes/intranet'
import { Route as FleetStatusRouteImport } from './routes/fleet-status'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const IntranetRoute = IntranetRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/intranet.lazy').then((d) => d.Route))
const FleetStatusRoute = FleetStatusRouteImport.update({
  id: '/fleet-status',
  path: '/fleet-status',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/fleet-status.lazy').then((d) => d.Route))
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/financial.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financial': typeof FinancialRoute
  '/fleet-status': typeof FleetStatusRoute
  '/intranet': typeof IntranetRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financial': typeof FinancialRoute
  '/fleet-status': typeof FleetStatusRoute
  '/intranet': typeof IntranetRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/financial': typeof FinancialRoute
  '/fleet-status': typeof FleetStatusRoute
  '/intranet': typeof IntranetRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/financial' | '/fleet-status' | '/intranet' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/financial' | '/fleet-status' | '/intranet' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/financial'
    | '/fleet-status'
    | '/intranet'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancialRoute: typeof FinancialRoute
  FleetStatusRoute: typeof FleetStatusRoute
  IntranetRoute: typeof IntranetRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intranet': {
      id: '/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof IntranetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-status': {
      id: '/fleet-status'
      path: '/fleet-status'
      fullPath: '/fleet-status'
      preLoaderRoute: typeof FleetStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancialRoute: FinancialRoute,
  FleetStatusRoute: FleetStatusRoute,
  IntranetRoute: IntranetRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
