/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as IntranetRouteImport } from './routes/intranet'
import { Route as FleetStatusRouteImport } from './routes/fleet-status'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsTenantsRouteImport } from './routes/settings/tenants'
import { Route as SettingsJobsRouteImport } from './routes/settings/jobs'
import { Route as SettingsEventsRouteImport } from './routes/settings/events'
import { Route as SettingsConfigurationRouteImport } from './routes/settings/configuration'
import { Route as SettingsAuthenticationRouteImport } from './routes/settings/authentication'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kiosk.lazy').then((d) => d.Route))
const IntranetRoute = IntranetRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/intranet.lazy').then((d) => d.Route))
const FleetStatusRoute = FleetStatusRouteImport.update({
  id: '/fleet-status',
  path: '/fleet-status',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/fleet-status.lazy').then((d) => d.Route))
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/financial.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings/users.lazy').then((d) => d.Route),
)
const SettingsTenantsRoute = SettingsTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings/tenants.lazy').then((d) => d.Route),
)
const SettingsJobsRoute = SettingsJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() => import('./routes/settings/jobs.lazy').then((d) => d.Route))
const SettingsEventsRoute = SettingsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings/events.lazy').then((d) => d.Route),
)
const SettingsConfigurationRoute = SettingsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings/configuration.lazy').then((d) => d.Route),
)
const SettingsAuthenticationRoute = SettingsAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings/authentication.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financial': typeof FinancialRoute
  '/fleet-status': typeof FleetStatusRoute
  '/intranet': typeof IntranetRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/jobs': typeof SettingsJobsRoute
  '/settings/tenants': typeof SettingsTenantsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financial': typeof FinancialRoute
  '/fleet-status': typeof FleetStatusRoute
  '/intranet': typeof IntranetRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/jobs': typeof SettingsJobsRoute
  '/settings/tenants': typeof SettingsTenantsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/financial': typeof FinancialRoute
  '/fleet-status': typeof FleetStatusRoute
  '/intranet': typeof IntranetRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/jobs': typeof SettingsJobsRoute
  '/settings/tenants': typeof SettingsTenantsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/financial'
    | '/fleet-status'
    | '/intranet'
    | '/kiosk'
    | '/login'
    | '/settings'
    | '/settings/authentication'
    | '/settings/configuration'
    | '/settings/events'
    | '/settings/jobs'
    | '/settings/tenants'
    | '/settings/users'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/financial'
    | '/fleet-status'
    | '/intranet'
    | '/kiosk'
    | '/login'
    | '/settings/authentication'
    | '/settings/configuration'
    | '/settings/events'
    | '/settings/jobs'
    | '/settings/tenants'
    | '/settings/users'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/financial'
    | '/fleet-status'
    | '/intranet'
    | '/kiosk'
    | '/login'
    | '/settings'
    | '/settings/authentication'
    | '/settings/configuration'
    | '/settings/events'
    | '/settings/jobs'
    | '/settings/tenants'
    | '/settings/users'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancialRoute: typeof FinancialRoute
  FleetStatusRoute: typeof FleetStatusRoute
  IntranetRoute: typeof IntranetRoute
  KioskRoute: typeof KioskRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intranet': {
      id: '/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof IntranetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-status': {
      id: '/fleet-status'
      path: '/fleet-status'
      fullPath: '/fleet-status'
      preLoaderRoute: typeof FleetStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tenants': {
      id: '/settings/tenants'
      path: '/tenants'
      fullPath: '/settings/tenants'
      preLoaderRoute: typeof SettingsTenantsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/jobs': {
      id: '/settings/jobs'
      path: '/jobs'
      fullPath: '/settings/jobs'
      preLoaderRoute: typeof SettingsJobsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/events': {
      id: '/settings/events'
      path: '/events'
      fullPath: '/settings/events'
      preLoaderRoute: typeof SettingsEventsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/configuration': {
      id: '/settings/configuration'
      path: '/configuration'
      fullPath: '/settings/configuration'
      preLoaderRoute: typeof SettingsConfigurationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/authentication': {
      id: '/settings/authentication'
      path: '/authentication'
      fullPath: '/settings/authentication'
      preLoaderRoute: typeof SettingsAuthenticationRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAuthenticationRoute: typeof SettingsAuthenticationRoute
  SettingsConfigurationRoute: typeof SettingsConfigurationRoute
  SettingsEventsRoute: typeof SettingsEventsRoute
  SettingsJobsRoute: typeof SettingsJobsRoute
  SettingsTenantsRoute: typeof SettingsTenantsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAuthenticationRoute: SettingsAuthenticationRoute,
  SettingsConfigurationRoute: SettingsConfigurationRoute,
  SettingsEventsRoute: SettingsEventsRoute,
  SettingsJobsRoute: SettingsJobsRoute,
  SettingsTenantsRoute: SettingsTenantsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancialRoute: FinancialRoute,
  FleetStatusRoute: FleetStatusRoute,
  IntranetRoute: IntranetRoute,
  KioskRoute: KioskRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
