// <auto-generated />
using System;
using System.Collections.Generic;
using Adwais.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adwais.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260706181335_ConsolidateNewsletterAndCommunityPost")]
    partial class ConsolidateNewsletterAndCommunityPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adwais.Domain.Entities.GlobalConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveSubscription")
                        .HasColumnType("text")
                        .HasColumnName("active_subscription");

                    b.Property<double?>("DefaultUptimeSla")
                        .HasColumnType("double precision")
                        .HasColumnName("default_uptime_sla");

                    b.Property<int>("FeedFetchIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("feed_fetch_interval_hours");

                    b.Property<DateTimeOffset?>("LastPolled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<int?>("LatencyDegradedFloor")
                        .HasColumnType("integer")
                        .HasColumnName("latency_degraded_floor");

                    b.Property<int>("LatencyFetchIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("latency_fetch_interval_minutes");

                    b.Property<bool>("LitiumFetchEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("litium_fetch_enabled");

                    b.Property<int>("LitiumFetchIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("litium_fetch_interval_minutes");

                    b.Property<int?>("MonitorsCount")
                        .HasColumnType("integer")
                        .HasColumnName("monitors_count");

                    b.Property<int?>("MonitorsLimit")
                        .HasColumnType("integer")
                        .HasColumnName("monitors_limit");

                    b.Property<int>("SystemEventRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("system_event_retention_days");

                    b.Property<int>("UptimeFetchIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("uptime_fetch_interval_minutes");

                    b.Property<string>("UptimeRobotApiKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("uptime_robot_api_key");

                    b.Property<bool>("UptimeRobotFetchEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("uptime_robot_fetch_enabled");

                    b.Property<int>("UserStatsFetchIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("user_stats_fetch_interval_minutes");

                    b.HasKey("Id")
                        .HasName("pk_global_config");

                    b.ToTable("global_config", null, t =>
                        {
                            t.HasCheckConstraint("CK_GlobalConfig_SingleRow", "\"id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeedFetchIntervalHours = 2,
                            LatencyFetchIntervalMinutes = 10,
                            LitiumFetchEnabled = true,
                            LitiumFetchIntervalMinutes = 60,
                            SystemEventRetentionDays = 2,
                            UptimeFetchIntervalMinutes = 60,
                            UptimeRobotFetchEnabled = true,
                            UserStatsFetchIntervalMinutes = 60
                        });
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.CommunityPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_community_post");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_community_post_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_community_post_user_id");

                    b.ToTable("community_post", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.FeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid?>("FeedSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("feed_source_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("link");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_feed_item");

                    b.HasIndex("FeedSourceId")
                        .HasDatabaseName("ix_feed_item_feed_source_id");

                    b.HasIndex("Link")
                        .IsUnique()
                        .HasDatabaseName("ix_feed_item_link");

                    b.HasIndex("PublishDate")
                        .HasDatabaseName("ix_feed_item_publish_date");

                    b.ToTable("feed_item", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.FeedSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_sync_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_feed_source");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_feed_source_url");

                    b.ToTable("feed_source", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.OfficeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_important");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("None")
                        .HasColumnName("recurrence");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_office_event");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("ix_office_event_end_time");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_office_event_start_time");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_office_event_user_id");

                    b.ToTable("office_event", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.KioskDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("activation_code");

                    b.Property<DateTimeOffset>("ActivationCodeExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activation_code_expires");

                    b.Property<DateTimeOffset?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorized_at");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsAuthorized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_authorized");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_devices");

                    b.HasIndex("ActivationCode")
                        .HasDatabaseName("ix_kiosk_devices_activation_code");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_devices_device_id");

                    b.ToTable("kiosk_devices", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityGlobalRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double?>("UptimePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_percentage");

                    b.HasKey("Date");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_availability_global_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityMonitorRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.Property<double?>("UptimePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_percentage");

                    b.HasKey("Date", "MonitorId");

                    b.HasIndex("MonitorId");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_availability_monitor_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityTenantRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<double?>("UptimePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_percentage");

                    b.HasKey("Date", "TenantId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_daily_availability_tenant_rollups_tenant_id");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_availability_tenant_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyGlobalRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.HasKey("Date");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_global_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyMonitorRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.HasKey("Date", "MonitorId");

                    b.HasIndex("MonitorId");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_monitor_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyTenantRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.HasKey("Date", "TenantId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_daily_latency_tenant_rollups_tenant_id");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_tenant_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.MonitorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.Property<double?>("UptimePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_percentage");

                    b.HasKey("Id")
                        .HasName("pk_monitor_availability");

                    b.HasIndex("MonitorId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_monitor_availability_monitor_id_date");

                    b.ToTable("monitor_availability", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.ResponseTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.HasKey("Id")
                        .HasName("pk_response_time");

                    b.HasIndex("MonitorId")
                        .HasDatabaseName("ix_response_time_monitor_id");

                    b.ToTable("response_time", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTimeOffset?>("LastLatencyUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_latency_update");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<DateTimeOffset?>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<DateTimeOffset?>("LastUptimeUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_uptime_update");

                    b.Property<int?>("LatencyDegradedFloor")
                        .HasColumnType("integer")
                        .HasColumnName("latency_degraded_floor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UpdateInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300)
                        .HasColumnName("update_interval");

                    b.Property<bool>("UptimeMonitorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("uptime_monitor_enabled");

                    b.Property<double?>("UptimeSla")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_sla");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_monitor");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_monitor_tenant_id");

                    b.ToTable("monitor", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.DailyFinancialGlobalRollup", b =>
                {
                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<decimal>("GlobalRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("global_revenue");

                    b.Property<decimal>("GlobalVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("global_volume");

                    b.HasKey("CreatedDate");

                    b.ToTable((string)null);

                    b.ToView("v_mat_financial_daily_global_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.DailyFinancialTenantRollup", b =>
                {
                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric")
                        .HasColumnName("revenue");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("CreatedDate", "TenantId");

                    b.ToTable((string)null);

                    b.ToView("v_mat_financial_daily_tenant_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("LitiumOrderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("litium_order_id");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("order_state");

                    b.Property<Guid?>("OrganizationSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_system_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalValueExcVat")
                        .HasColumnType("numeric")
                        .HasColumnName("total_value_exc_vat");

                    b.Property<decimal>("TotalValueIncVat")
                        .HasColumnType("numeric")
                        .HasColumnName("total_value_inc_vat");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedDate", "TenantId")
                        .HasDatabaseName("idx_orders_composite_dash");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedDate", "TenantId"), new[] { "TotalValueIncVat" });

                    b.HasIndex("TenantId", "CreatedDate")
                        .HasDatabaseName("idx_orders_tenant_isolated");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "CreatedDate"), new[] { "TotalValueIncVat" });

                    b.HasIndex("TenantId", "TotalValueIncVat")
                        .HasDatabaseName("idx_orders_value_dist");

                    b.HasIndex("TenantId", "CreatedDate", "OrderState")
                        .HasDatabaseName("ix_orders_tenant_id_created_date_order_state");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.SystemEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_system_event");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_system_event_tenant_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_system_event_timestamp");

                    b.ToTable("system_event", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("CurrentlyFetching")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("currently_fetching");

                    b.Property<DateTimeOffset?>("FetchedFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_from");

                    b.Property<DateTimeOffset?>("FetchedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_until");

                    b.Property<DateTimeOffset?>("LastPolled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<string>("LitiumBaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("litium_base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<bool>("OrderFetchingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("order_fetching_enabled");

                    b.Property<string>("ServiceAccountToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("service_account_token");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Mixed")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CurrentlyFetching = false,
                            Name = "System (unassigned monitors)",
                            OrderFetchingEnabled = false,
                            Type = "Mixed"
                        });
                });

            modelBuilder.Entity("Adwais.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EntraObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_object_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entra_object_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Email = "system@adwais.local",
                            Name = "System",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.CommunityPost", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.FeedItem", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Intranet.FeedSource", "FeedSource")
                        .WithMany("FeedItems")
                        .HasForeignKey("FeedSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_feed_item_feed_source_feed_source_id");

                    b.Navigation("FeedSource");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.OfficeEvent", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_office_event_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityMonitorRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_availability_monitor_rollups_monitors_uptime_monitor_");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityTenantRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_availability_tenant_rollups_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyMonitorRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_latency_monitor_rollups_monitors_uptime_monitor_id");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyTenantRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_latency_tenant_rollups_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.MonitorAvailability", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monitor_availability_monitors_monitor_id");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.ResponseTime", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany("ResponseTimes")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_response_time_monitors_monitor_id");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Monitors")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_monitor_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.Order", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Orders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.SystemEvent", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_system_event_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.FeedSource", b =>
                {
                    b.Navigation("FeedItems");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.Navigation("ResponseTimes");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Monitors");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
