// <auto-generated />
using System;
using Adwais.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adwais.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260505132337_BaselineSchema")]
    partial class BaselineSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adwais.Domain.Entities.GlobalConfig", b =>
                {
                    b.Property<string>("ActiveSubscription")
                        .HasColumnType("text")
                        .HasColumnName("active_subscription");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastPolled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled");

                    b.Property<int?>("LatencyDegradedFloor")
                        .HasColumnType("integer")
                        .HasColumnName("latency_degraded_floor");

                    b.Property<int>("LitiumRateLimit")
                        .HasColumnType("integer")
                        .HasColumnName("litium_rate_limit");

                    b.Property<int>("MonitorsCount")
                        .HasColumnType("integer")
                        .HasColumnName("monitors_count");

                    b.Property<int>("MonitorsLimit")
                        .HasColumnType("integer")
                        .HasColumnName("monitors_limit");

                    b.Property<string>("UptimeRobotApiKey")
                        .HasColumnType("text")
                        .HasColumnName("uptime_robot_api_key");

                    b.Property<int>("UptimeRobotRateLimit")
                        .HasColumnType("integer")
                        .HasColumnName("uptime_robot_rate_limit");

                    b.ToTable("global_config", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyGlobalRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.HasKey("Date");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_global_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyMonitorRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.Property<int>("UptimeMonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("uptime_monitor_id");

                    b.HasKey("Date", "MonitorId");

                    b.HasIndex("UptimeMonitorId")
                        .HasDatabaseName("ix_daily_latency_monitor_rollups_uptime_monitor_id");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_monitor_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyTenantRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.HasKey("Date", "TenantId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_daily_latency_tenant_rollups_tenant_id");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_tenant_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.ResponseTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.HasKey("Id")
                        .HasName("pk_response_time");

                    b.HasIndex("MonitorId")
                        .HasDatabaseName("ix_response_time_monitor_id");

                    b.ToTable("response_time", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("UptimeMonitorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("uptime_monitor_enabled");

                    b.Property<double?>("UptimeSla")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_sla");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_monitor");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_monitor_tenant_id");

                    b.ToTable("monitor", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.DailyFinancialGlobalRollup", b =>
                {
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long>("GlobalRevenue")
                        .HasColumnType("bigint")
                        .HasColumnName("global_revenue");

                    b.Property<long>("GlobalVolume")
                        .HasColumnType("bigint")
                        .HasColumnName("global_volume");

                    b.HasKey("CreatedDate");

                    b.ToTable((string)null);

                    b.ToView("v_mat_financial_daily_global_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.DailyFinancialTenantRollup", b =>
                {
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Revenue")
                        .HasColumnType("bigint")
                        .HasColumnName("revenue");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("CreatedDate", "TenantId");

                    b.ToTable((string)null);

                    b.ToView("v_mat_financial_daily_tenant_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("LitiumOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("litium_order_id");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_state");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalValueExcVat")
                        .HasColumnType("integer")
                        .HasColumnName("total_value_exc_vat");

                    b.Property<int>("TotalValueIncVat")
                        .HasColumnType("integer")
                        .HasColumnName("total_value_inc_vat");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedDate", "TenantId")
                        .HasDatabaseName("idx_orders_composite_dash");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedDate", "TenantId"), new[] { "TotalValueIncVat" });

                    b.HasIndex("TenantId", "CreatedDate")
                        .HasDatabaseName("idx_orders_tenant_isolated");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "CreatedDate"), new[] { "TotalValueIncVat" });

                    b.HasIndex("TenantId", "LitiumOrderId")
                        .IsUnique()
                        .HasDatabaseName("uq_orders_tenant_litium");

                    b.HasIndex("TenantId", "TotalValueIncVat")
                        .HasDatabaseName("idx_orders_value_dist");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("CurrentlyFetching")
                        .HasColumnType("boolean")
                        .HasColumnName("currently_fetching");

                    b.Property<DateTimeOffset?>("FetchedFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_from");

                    b.Property<DateTimeOffset?>("FetchedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_until");

                    b.Property<DateTimeOffset?>("LastPolled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled");

                    b.Property<string>("LitiumBaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("litium_base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer")
                        .HasColumnName("order_count");

                    b.Property<bool>("OrderFetchingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("order_fetching_enabled");

                    b.Property<bool?>("PingReachable")
                        .HasColumnType("boolean")
                        .HasColumnName("ping_reachable");

                    b.Property<string>("ServiceAccountToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_account_token");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyMonitorRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany()
                        .HasForeignKey("UptimeMonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_latency_monitor_rollups_monitors_uptime_monitor_id");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyTenantRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_latency_tenant_rollups_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.ResponseTime", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany("ResponseTimes")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_response_time_monitor_monitor_id");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Monitors")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monitor_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.Order", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Orders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.Navigation("ResponseTimes");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Monitors");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}


