// Part of the ADWAIS project, under the Business Source License 1.1.
// See /LICENSE for license information.
// SPDX-License-Identifier: BUSL-1.1

// <auto-generated />
using System;
using System.Collections.Generic;
using Adwais.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adwais.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adwais.Domain.Entities.GlobalConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveSubscription")
                        .HasColumnType("text")
                        .HasColumnName("active_subscription");

                    b.Property<int>("FeedFetchIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("feed_fetch_interval_hours");

                    b.Property<DateTimeOffset?>("LastPolled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<int>("LatencyFetchIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("latency_fetch_interval_minutes");

                    b.Property<bool>("MonitoringFetchEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("monitoring_fetch_enabled");

                    b.Property<string>("MonitoringProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("uptimerobot")
                        .HasColumnName("monitoring_provider");

                    b.Property<string>("MonitoringProviderSettings")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("monitoring_provider_settings");

                    b.Property<int?>("MonitorsCount")
                        .HasColumnType("integer")
                        .HasColumnName("monitors_count");

                    b.Property<int?>("MonitorsLimit")
                        .HasColumnType("integer")
                        .HasColumnName("monitors_limit");

                    b.Property<bool>("OrderFetchEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("order_fetch_enabled");

                    b.Property<int>("OrderFetchIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("order_fetch_interval_minutes");

                    b.Property<string>("ReportingTimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Europe/Stockholm")
                        .HasColumnName("reporting_time_zone_id");

                    b.Property<int>("SystemEventRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("system_event_retention_days");

                    b.Property<int>("UptimeFetchIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("uptime_fetch_interval_minutes");

                    b.Property<int>("UserStatsFetchIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("user_stats_fetch_interval_minutes");

                    b.Property<int>("WeatherFetchIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("weather_fetch_interval_minutes");

                    b.Property<string>("WeatherLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Karlstad")
                        .HasColumnName("weather_location");

                    b.HasKey("Id")
                        .HasName("pk_global_config");

                    b.ToTable("global_config", null, t =>
                        {
                            t.HasCheckConstraint("CK_GlobalConfig_SingleRow", "\"id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeedFetchIntervalHours = 2,
                            LatencyFetchIntervalMinutes = 10,
                            MonitoringFetchEnabled = true,
                            MonitoringProvider = "uptimerobot",
                            OrderFetchEnabled = true,
                            OrderFetchIntervalMinutes = 60,
                            ReportingTimeZoneId = "Europe/Stockholm",
                            SystemEventRetentionDays = 2,
                            UptimeFetchIntervalMinutes = 60,
                            UserStatsFetchIntervalMinutes = 60,
                            WeatherFetchIntervalMinutes = 15,
                            WeatherLocation = "Karlstad"
                        });
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.BulletinPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bulletin_post");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_bulletin_post_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bulletin_post_user_id");

                    b.ToTable("bulletin_post", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CalendarSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_subscription_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("General")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalUid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_uid");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("None")
                        .HasColumnName("recurrence");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_calendar_event");

                    b.HasIndex("CalendarSubscriptionId")
                        .HasDatabaseName("ix_calendar_event_calendar_subscription_id");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("ix_calendar_event_end_time");

                    b.HasIndex("ExternalUid")
                        .HasDatabaseName("ix_calendar_event_external_uid");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_calendar_event_start_time");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_calendar_event_user_id");

                    b.ToTable("calendar_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_calendar_event_event_type", "\"event_type\" IN ('General', 'Meeting', 'Fika', 'Social', 'Birthday', 'GoLive', 'ExternalSync')");

                            t.HasCheckConstraint("ck_calendar_event_recurrence", "\"recurrence\" IN ('None', 'Daily', 'Weekly', 'Monthly', 'Yearly')");
                        });
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.CalendarSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_sync_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_calendar_subscription");

                    b.ToTable("calendar_subscription", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.FeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid?>("FeedSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("feed_source_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("link");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_feed_item");

                    b.HasIndex("FeedSourceId")
                        .HasDatabaseName("ix_feed_item_feed_source_id");

                    b.HasIndex("Link")
                        .IsUnique()
                        .HasDatabaseName("ix_feed_item_link");

                    b.HasIndex("PublishDate")
                        .HasDatabaseName("ix_feed_item_publish_date");

                    b.ToTable("feed_item", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.FeedSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_sync_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_feed_source");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_feed_source_url");

                    b.ToTable("feed_source", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.KioskDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("activation_code");

                    b.Property<DateTimeOffset>("ActivationCodeExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activation_code_expires");

                    b.Property<DateTimeOffset?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorized_at");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsAuthorized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_authorized");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_devices");

                    b.HasIndex("ActivationCode")
                        .HasDatabaseName("ix_kiosk_devices_activation_code");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_devices_device_id");

                    b.ToTable("kiosk_devices", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityGlobalRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double?>("UptimePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_percentage");

                    b.HasKey("Date");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_availability_global_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityMonitorRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.Property<double?>("UptimePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_percentage");

                    b.HasKey("Date", "MonitorId");

                    b.HasIndex("MonitorId");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_availability_monitor_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityTenantRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<double?>("UptimePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_percentage");

                    b.HasKey("Date", "TenantId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_daily_availability_tenant_rollups_tenant_id");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_availability_tenant_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyGlobalRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision")
                        .HasColumnName("p10");

                    b.Property<double?>("P90")
                        .HasColumnType("double precision")
                        .HasColumnName("p90");

                    b.HasKey("Date");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_global_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyMonitorRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision")
                        .HasColumnName("p10");

                    b.Property<double?>("P90")
                        .HasColumnType("double precision")
                        .HasColumnName("p90");

                    b.HasKey("Date", "MonitorId");

                    b.HasIndex("MonitorId");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_monitor_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyTenantRollup", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision")
                        .HasColumnName("p10");

                    b.Property<double?>("P90")
                        .HasColumnType("double precision")
                        .HasColumnName("p90");

                    b.HasKey("Date", "TenantId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_daily_latency_tenant_rollups_tenant_id");

                    b.ToTable((string)null);

                    b.ToView("v_mat_daily_latency_tenant_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.MonitorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<bool>("IsFinalized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_finalized");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.Property<double?>("UptimePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_percentage");

                    b.HasKey("Id")
                        .HasName("pk_monitor_availability");

                    b.HasIndex("MonitorId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_monitor_availability_monitor_id_date");

                    b.ToTable("monitor_availability", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.ResponseTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double?>("Highest")
                        .HasColumnType("double precision")
                        .HasColumnName("highest");

                    b.Property<double?>("Lowest")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest");

                    b.Property<int>("MonitorId")
                        .HasColumnType("integer")
                        .HasColumnName("monitor_id");

                    b.HasKey("Id")
                        .HasName("pk_response_time");

                    b.HasIndex("MonitorId")
                        .HasDatabaseName("ix_response_time_monitor_id");

                    b.ToTable("response_time", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long?>("CurrentStateDurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("current_state_duration_seconds");

                    b.Property<DateTimeOffset?>("DomainExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("domain_expires_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("http_method");

                    b.Property<string>("LastIncidentCause")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_incident_cause");

                    b.Property<long?>("LastIncidentDurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("last_incident_duration_seconds");

                    b.Property<string>("LastIncidentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_incident_id");

                    b.Property<string>("LastIncidentReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_incident_reason");

                    b.Property<DateTimeOffset?>("LastIncidentStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_incident_started_at");

                    b.Property<string>("LastIncidentStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_incident_status");

                    b.Property<DateTimeOffset?>("LastLatencyUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_latency_update");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<DateTimeOffset?>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<DateTimeOffset?>("LastUptimeUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_uptime_update");

                    b.Property<int?>("LatencyDegradedFloor")
                        .HasColumnType("integer")
                        .HasColumnName("latency_degraded_floor");

                    b.PrimitiveCollection<List<string>>("MonitoredRegions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("monitored_regions")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("SslExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ssl_expires_at");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("HTTP")
                        .HasColumnName("type");

                    b.Property<int>("UpdateInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300)
                        .HasColumnName("update_interval");

                    b.Property<bool>("UptimeMonitorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("uptime_monitor_enabled");

                    b.Property<double?>("UptimeSla")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_sla");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_monitor");

                    b.HasIndex("TenantId", "Provider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_monitor_tenant_id_provider_external_id");

                    b.ToTable("monitor", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.DailyFinancialGlobalRollup", b =>
                {
                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<decimal>("GlobalRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("global_revenue");

                    b.Property<decimal>("GlobalVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("global_volume");

                    b.HasKey("CreatedDate");

                    b.ToTable((string)null);

                    b.ToView("v_mat_financial_daily_global_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.DailyFinancialTenantRollup", b =>
                {
                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric")
                        .HasColumnName("revenue");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("CreatedDate", "TenantId");

                    b.ToTable((string)null);

                    b.ToView("v_mat_financial_daily_tenant_rollup", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("order_state");

                    b.Property<Guid?>("OrganizationSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_system_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalValueExcVat")
                        .HasColumnType("numeric")
                        .HasColumnName("total_value_exc_vat");

                    b.Property<decimal>("TotalValueIncVat")
                        .HasColumnType("numeric")
                        .HasColumnName("total_value_inc_vat");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedDate", "TenantId")
                        .HasDatabaseName("idx_orders_composite_dash");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedDate", "TenantId"), new[] { "TotalValueIncVat" });

                    b.HasIndex("TenantId", "CreatedDate")
                        .HasDatabaseName("idx_orders_tenant_isolated");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "CreatedDate"), new[] { "TotalValueIncVat" });

                    b.HasIndex("TenantId", "TotalValueIncVat")
                        .HasDatabaseName("idx_orders_value_dist");

                    b.HasIndex("TenantId", "CreatedDate", "OrderState")
                        .HasDatabaseName("ix_orders_tenant_id_created_date_order_state");

                    b.HasIndex("TenantId", "Provider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_tenant_id_provider_external_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.SystemEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_system_event");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_system_event_tenant_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_system_event_timestamp");

                    b.ToTable("system_event", (string)null);
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("CurrentlyFetching")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("currently_fetching");

                    b.Property<DateTimeOffset?>("FetchedFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_from");

                    b.Property<DateTimeOffset?>("FetchedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_until");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<DateTimeOffset?>("LastPolled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<bool>("OrderFetchingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("order_fetching_enabled");

                    b.Property<string>("OrderProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("litium")
                        .HasColumnName("order_provider");

                    b.Property<string>("OrderProviderSettings")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("order_provider_settings");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Mixed")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CurrentlyFetching = false,
                            Name = "System (unassigned monitors)",
                            OrderFetchingEnabled = false,
                            OrderProvider = "litium",
                            Type = "Mixed"
                        });
                });

            modelBuilder.Entity("Adwais.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CalendarFeedToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("calendar_feed_token");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubjectId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_subject_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CalendarFeedToken")
                        .IsUnique()
                        .HasDatabaseName("ix_users_calendar_feed_token");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ExternalSubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_subject_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Email = "system@adwais.local",
                            Name = "System",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.BulletinPost", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bulletin_post_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.CalendarEvent", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Intranet.CalendarSubscription", "CalendarSubscription")
                        .WithMany("Events")
                        .HasForeignKey("CalendarSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_calendar_event_calendar_subscriptions_calendar_subscription");

                    b.HasOne("Adwais.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_calendar_event_users_user_id");

                    b.Navigation("CalendarSubscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.FeedItem", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Intranet.FeedSource", "FeedSource")
                        .WithMany("FeedItems")
                        .HasForeignKey("FeedSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_feed_item_feed_source_feed_source_id");

                    b.Navigation("FeedSource");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityMonitorRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_availability_monitor_rollups_monitors_uptime_monitor_");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyAvailabilityTenantRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_availability_tenant_rollups_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyMonitorRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_latency_monitor_rollups_monitors_uptime_monitor_id");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.DailyLatencyTenantRollup", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_latency_tenant_rollups_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.MonitorAvailability", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monitor_availability_monitors_monitor_id");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.ResponseTime", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Monitoring.UptimeMonitor", "UptimeMonitor")
                        .WithMany("ResponseTimes")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_response_time_monitors_monitor_id");

                    b.Navigation("UptimeMonitor");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Monitors")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_monitor_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.OrderData.Order", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Orders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.SystemEvent", b =>
                {
                    b.HasOne("Adwais.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_system_event_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.CalendarSubscription", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Intranet.FeedSource", b =>
                {
                    b.Navigation("FeedItems");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Monitoring.UptimeMonitor", b =>
                {
                    b.Navigation("ResponseTimes");
                });

            modelBuilder.Entity("Adwais.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Monitors");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
